### ISSUE TITLE
Gulp build html parser

### ISSUE THREAD

**Issue by jonathan0211** [CrackerakiUA/ui-cropper#45]
Hello I am getting this error on gulp build
`    at new HTMLParser (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/html-minifier/src/htmlminifier.js:861:3)
    at Object.exports.minify (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/html-minifier/src/htmlminifier.js:1216:10)
    at objectAssign.fileName (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/gulp-htmlmin/index.js:22:39)
    at module.exports (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/gulp-htmlmin/index.js:21:9)
    at Transform.htmlminTransform [as _transform] (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/gulp-htmlmin/index.js:51:7)
    at Transform._read (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Transform._write (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at Transform.Writable.write (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at write (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/jonathan/projects/consvita/agronomico/agro-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
`

**Comment by jonathan0211** [comment]
Please ignore this
